export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_ERROR: 500,
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  USER_BANNED: 'USER_BANNED',
  USER_INACTIVE: 'USER_INACTIVE',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  MISSING_TOKEN: 'MISSING_TOKEN',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  OAUTH_FAILED: 'OAUTH_FAILED',
} as const;

export const EMAIL_ERROR_CODES = {
  CODE_EXPIRED: 'CODE_EXPIRED',
  CODE_INVALID: 'CODE_INVALID',
  CODE_ALREADY_USED: 'CODE_ALREADY_USED',
  RESEND_COOLDOWN: 'RESEND_COOLDOWN',
  MAX_CODES_EXCEEDED: 'MAX_CODES_EXCEEDED',
  VERIFICATION_REQUIRED: 'VERIFICATION_REQUIRED',
  VERIFICATION_TOKEN_INVALID: 'VERIFICATION_TOKEN_INVALID',
  VERIFICATION_TOKEN_EXPIRED: 'VERIFICATION_TOKEN_EXPIRED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
} as const;

export const DOCUMENT_ERROR_CODES = {
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  DOWNLOAD_FAILED: 'DOWNLOAD_FAILED',
  STORAGE_ERROR: 'STORAGE_ERROR',
  ACCESS_DENIED: 'ACCESS_DENIED',
} as const;

export const KNOWLEDGE_BASE_ERROR_CODES = {
  KNOWLEDGE_BASE_NOT_FOUND: 'KNOWLEDGE_BASE_NOT_FOUND',
  KNOWLEDGE_BASE_ACCESS_DENIED: 'KNOWLEDGE_BASE_ACCESS_DENIED',
  EMBEDDING_CONFIG_IMMUTABLE: 'EMBEDDING_CONFIG_IMMUTABLE',
  INVALID_EMBEDDING_PROVIDER: 'INVALID_EMBEDDING_PROVIDER',
} as const;

export const LLM_ERROR_CODES = {
  LLM_CONFIG_NOT_FOUND: 'LLM_CONFIG_NOT_FOUND',
  LLM_PROVIDER_NOT_CONFIGURED: 'LLM_PROVIDER_NOT_CONFIGURED',
  LLM_API_KEY_REQUIRED: 'LLM_API_KEY_REQUIRED',
  LLM_API_KEY_INVALID: 'LLM_API_KEY_INVALID',
  LLM_CONNECTION_FAILED: 'LLM_CONNECTION_FAILED',
  LLM_MODEL_NOT_FOUND: 'LLM_MODEL_NOT_FOUND',
  LLM_RATE_LIMITED: 'LLM_RATE_LIMITED',
  LLM_CONTEXT_TOO_LONG: 'LLM_CONTEXT_TOO_LONG',
  LLM_GENERATION_FAILED: 'LLM_GENERATION_FAILED',
  LLM_ENCRYPTION_FAILED: 'LLM_ENCRYPTION_FAILED',
  LLM_DECRYPTION_FAILED: 'LLM_DECRYPTION_FAILED',
} as const;

export const CHAT_ERROR_CODES = {
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_ACCESS_DENIED: 'CONVERSATION_ACCESS_DENIED',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  EMPTY_MESSAGE: 'EMPTY_MESSAGE',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  STREAMING_FAILED: 'STREAMING_FAILED',
  RAG_SEARCH_FAILED: 'RAG_SEARCH_FAILED',
  CHAT_SEARCH_INVALID_QUERY: 'CHAT_SEARCH_INVALID_QUERY',
  CHAT_SEARCH_FAILED: 'CHAT_SEARCH_FAILED',
} as const;

export const DOCUMENT_AI_ERROR_CODES = {
  CONTENT_EMPTY: 'DOCUMENT_AI_CONTENT_EMPTY',
  CONTENT_TOO_LARGE: 'DOCUMENT_AI_CONTENT_TOO_LARGE',
  SUMMARY_FAILED: 'DOCUMENT_AI_SUMMARY_FAILED',
  ANALYSIS_FAILED: 'DOCUMENT_AI_ANALYSIS_FAILED',
  GENERATION_FAILED: 'DOCUMENT_AI_GENERATION_FAILED',
  STREAMING_FAILED: 'DOCUMENT_AI_STREAMING_FAILED',
} as const;

export const ANNOTATION_ERROR_CODES = {
  ANNOTATION_NOT_FOUND: 'ANNOTATION_NOT_FOUND',
  ANNOTATION_ACCESS_DENIED: 'ANNOTATION_ACCESS_DENIED',
  INVALID_ANNOTATION_TYPE: 'INVALID_ANNOTATION_TYPE',
  INVALID_POSITION: 'INVALID_POSITION',
} as const;

export const AGENT_ERROR_CODES = {
  MAX_ITERATIONS_EXCEEDED: 'AGENT_MAX_ITERATIONS_EXCEEDED',
  TOOL_EXECUTION_FAILED: 'AGENT_TOOL_EXECUTION_FAILED',
  TOOL_NOT_FOUND: 'AGENT_TOOL_NOT_FOUND',
  WEB_SEARCH_FAILED: 'WEB_SEARCH_FAILED',
  WEB_SEARCH_NOT_CONFIGURED: 'WEB_SEARCH_NOT_CONFIGURED',
} as const;
